dbt_louvre:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('SUPABASE_HOST') }}"
      user: "{{ env_var('SUPABASE_USER') }}"
      password: "{{ env_var('SUPABASE_PASSWORD') }}"
      port: "{{ env_var('SUPABASE_PORT') | int }}"
      dbname: "{{ env_var('SUPABASE_DATABASE') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
